const express = require('express');
const router = express.Router();
const { Client, Environment } = require("square");
const Models = require("../../models/models.js");
//const uuidv4 = require('uuid/v4');

const { randomUUID } = require('crypto');
const { json } = require('express');

// Initializes Sandbox Environment. This is used for testing and will need to be changed
// to a different environment in the future.
const client = new Client({
  accessToken: process.env.SQUARE_ACCESS_TOKEN,
  environment: Environment.Sandbox,
});


async function getPrice() {
  const Misc = await Models.Misc.findOne();
  return Misc.Price;
}


// Initializes the paymentsApi in Sandbox Environment
const paymentsApi = client.paymentsApi;

// Retreives the token generated by front end. Generates an idempotencyKey (Which is a requirement
// for Square to create a secure payment)
router.post('/', async (req, res) => {

  const unitPrice = await getPrice();


  const token = req.body.sourceId.token;
  console.log(token);
  const idempotencyKey = randomUUID();

// Request body. Contains: Source token, idempotency key, cost of purchase, currency type
  const request_body = {
    sourceId: token,
    idempotencyKey: idempotencyKey,
    amountMoney: {
      amount: unitPrice,
      currency: 'CAD'
    }
  };

// Creates the secure payment using paymentsApi
  try{
    const { result: { payment } } = await paymentsApi.createPayment(request_body);
    const result = JSON.stringify(payment, (key, value) => {
      return typeof value === "bigint" ? parseInt(value) : value;
    }, 4);
  
// Returns payment information if successful else throws error
    var resData = JSON.parse(result);
    console.log(result);
    var receiptLink = resData.receiptUrl;
    console.log("Receipt Url: "+receiptLink);
    res.json({
      result
    });
  } catch (error) {
    console.log(error);
    res.json(error.result);
  }
});

module.exports = router;